// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGZ0tdK0WvPoPET2MWktJ5FFk3bLJdaQ',
    appId: '1:1021069922999:web:5a0d6b929cf6bcb8623332',
    messagingSenderId: '1021069922999',
    projectId: 'smart-attendee-51194',
    authDomain: 'smart-attendee-51194.firebaseapp.com',
    storageBucket: 'smart-attendee-51194.appspot.com',
    measurementId: 'G-8TVGV86WE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_Asne0ZKMgDqO8TZtp6Ph8o26yYysNs',
    appId: '1:1021069922999:android:a5e913b5a598ddcb623332',
    messagingSenderId: '1021069922999',
    projectId: 'smart-attendee-51194',
    storageBucket: 'smart-attendee-51194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKc9z6Rvg4X6nxsX1iHRq3QMRKz63Pxk',
    appId: '1:1021069922999:ios:df1b57fd02670605623332',
    messagingSenderId: '1021069922999',
    projectId: 'smart-attendee-51194',
    storageBucket: 'smart-attendee-51194.appspot.com',
    iosClientId: '1021069922999-krepqa8uesckbtvei3fanb154381eqvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAttendee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpKc9z6Rvg4X6nxsX1iHRq3QMRKz63Pxk',
    appId: '1:1021069922999:ios:df1b57fd02670605623332',
    messagingSenderId: '1021069922999',
    projectId: 'smart-attendee-51194',
    storageBucket: 'smart-attendee-51194.appspot.com',
    iosClientId: '1021069922999-krepqa8uesckbtvei3fanb154381eqvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAttendee',
  );
}
